package com.example.periodictableapp

object DummyData {
    fun generatePeriodicTableData():ArrayList<ModelPeriodicTable>{
        var periodicTableList=ArrayList<ModelPeriodicTable>()
        val periodictableModel1=ModelPeriodicTable(1,"H","Hydrogen",1.008,"1s^1",R.color.color1,true)
        val periodictableModel2=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel3=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel4=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel5=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel6=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel7=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel8=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel9=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel10=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel11=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel12=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel13=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel14=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel15=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel16=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel17=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel18=ModelPeriodicTable(2,"He","Helium",4.0003,"1s^2",R.color.color8,true)

        val periodictableModel19=ModelPeriodicTable(3,"Li","Litium",6.941,"[He]2s^1",R.color.color1,true)
        val periodictableModel20=ModelPeriodicTable(4,"Be","Beryllium",9.012,"2s^2",R.color.color2,true)
        val periodictableModel21=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel22=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel23=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel24=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel25=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel26=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel27=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel28=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel29=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel30=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel31=ModelPeriodicTable(5,"B","Boron",10.811,"2s^22s^1",R.color.color5,true)
        val periodictableModel32=ModelPeriodicTable(6,"C","Carbon",12.011,"2s^22p^2",R.color.color5,true)
        val periodictableModel33=ModelPeriodicTable(7,"N","Nitrogen",14.007,"2s^22p^3",R.color.color6,true)
        val periodictableModel34=ModelPeriodicTable(8,"O","Oxygen",15.999,"2s^22p^4",R.color.color6,true)
        val periodictableModel35=ModelPeriodicTable(9,"F","Fluorine",18.998,"2s^22p^5",R.color.color7,true)
        val periodictableModel36=ModelPeriodicTable(10,"Ne","Neon",20.180,"2s^22p^2",R.color.color8,true)

        val periodictableModel37=ModelPeriodicTable(11,"Na","Sodium",22.990,"[Na]3s^1",R.color.color1,true)
        val periodictableModel38=ModelPeriodicTable(12,"Mg","Magnesium",24.305,"3s^2",R.color.color2,true)
        val periodictableModel39=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel40=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel41=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel42=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel43=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel44=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel45=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel46=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel47=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel48=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel49=ModelPeriodicTable(13,"Al","Aliminium",26.982,"3s^23p^1",R.color.color4,true)
        val periodictableModel50=ModelPeriodicTable(14,"Si","Silicon",28.086,"3s^23p^2",R.color.color5,true)
        val periodictableModel51=ModelPeriodicTable(15,"P","Phosphorus",30.974,"3s^23p^3",R.color.color6,true)
        val periodictableModel52=ModelPeriodicTable(16,"S","Sulfur",32.066,"3s^23p^4",R.color.color6,true)
        val periodictableModel53=ModelPeriodicTable(17,"Cl","Chlorine",35.453,"3s^23p^5",R.color.color7,true)
        val periodictableModel54=ModelPeriodicTable(18,"Ar","Argon",39.948,"3s^23p^6",R.color.color8,true)

        val periodictableModel55=ModelPeriodicTable(19,"K","Potassium",39.098,"[Ar]4s^1",R.color.color1,true)
        val periodictableModel56=ModelPeriodicTable(20,"Ca","Calcium",40.078,"4s^2",R.color.color2,true)
        val periodictableModel57=ModelPeriodicTable(21,"Sc","Scandium",44.956,"3d^14s^2",R.color.color3,true)
        val periodictableModel58=ModelPeriodicTable(22,"Ti","Titanium",47.68,"3d^24s^2",R.color.color3,true)
        val periodictableModel59=ModelPeriodicTable(23,"V","Vanadium",50.942,"3d^34s^2",R.color.color3,true)
        val periodictableModel60=ModelPeriodicTable(24,"Cr","Chromium",51.996,"3d^54s^1",R.color.color3,true)
        val periodictableModel61=ModelPeriodicTable(25,"Mn","Manganese",54.938,"3d^54s^2",R.color.color3,true)
        val periodictableModel62=ModelPeriodicTable(26,"Fe","Iron",55.845,"3d^64s^2",R.color.color3,true)
        val periodictableModel63=ModelPeriodicTable(27,"Co","Kobal",58.933,"3d^74s^2",R.color.color3,true)
        val periodictableModel64=ModelPeriodicTable(28,"Ni","Nickel",58.693,"3d^84s^2",R.color.color3,true)
        val periodictableModel65=ModelPeriodicTable(29,"Cu","Copper",63.546,"3d^104s^1",R.color.color3,true)
        val periodictableModel66=ModelPeriodicTable(30,"Zn","Zinc",65.38,"3d^104s^2",R.color.color3,true)
        val periodictableModel67=ModelPeriodicTable(31,"Ga","Gallium",69.723,"3d^104s^24p^1",R.color.color4,true)
        val periodictableModel68=ModelPeriodicTable(32,"Ge","Germanium",72.631,"3d^104s^24p^2",R.color.color5,true)
        val periodictableModel69=ModelPeriodicTable(33,"As","Arsenic",74.922,"3d^104s^24p^3",R.color.color5,true)
        val periodictableModel70=ModelPeriodicTable(34,"Se","Selemium",78.971,"3d^104s^24p^4",R.color.color6,true)
        val periodictableModel71=ModelPeriodicTable(35,"Br","Bromine",79.904,"3d^104s^24p^5",R.color.color7,true)
        val periodictableModel72=ModelPeriodicTable(36,"Kr","Krypton",83.798,"3d^104s^24p^1",R.color.color8,true)

        val periodictableModel73=ModelPeriodicTable(37,"Rb","Rubidium",85.468,"[Kr]5s^1",R.color.color1,true)
        val periodictableModel74=ModelPeriodicTable(38,"Sr","Strontium",87.62,"5s^2",R.color.color2,true)
        val periodictableModel75=ModelPeriodicTable(39,"Y","Yttrium",88.906,"4d^15s^2",R.color.color3,true)
        val periodictableModel76=ModelPeriodicTable(40,"Zr","Zirconium",91.224,"4d^25s^2",R.color.color3,true)
        val periodictableModel77=ModelPeriodicTable(41,"Nb","Niobium",92.906,"4d^45s^1",R.color.color3,true)
        val periodictableModel78=ModelPeriodicTable(42,"Mo","Molybdenium",95.95,"4d^55s^1",R.color.color3,true)
        val periodictableModel79=ModelPeriodicTable(43,"Tc","Technetium",98.907,"4d^55s^2",R.color.color3,true)
        val periodictableModel80=ModelPeriodicTable(44,"Ru","Ruthenium",101.07,"4d^75s^1",R.color.color3,true)
        val periodictableModel81=ModelPeriodicTable(45,"Rh","Rhodium",102.906,"4d^85s^1",R.color.color3,true)
        val periodictableModel82=ModelPeriodicTable(46,"Pd","Palladium",106.42,"4d^10",R.color.color3,true)
        val periodictableModel83=ModelPeriodicTable(47,"Ag","Silver",107.868,"4d^105s^1",R.color.color3,true)
        val periodictableModel84=ModelPeriodicTable(48,"Cd","Cadmium",112.414,"4d^105s^2",R.color.color3,true)
        val periodictableModel85=ModelPeriodicTable(49,"In","Indium",114.819,"4d^105s^25p^1",R.color.color4,true)
        val periodictableModel86=ModelPeriodicTable(50,"Sn","Tin",118.711,"4d^105s^25p^2",R.color.color4,true)
        val periodictableModel87=ModelPeriodicTable(51,"Sb","Antimony",121.760,"4d^105s^25p^3",R.color.color5,true)
        val periodictableModel88=ModelPeriodicTable(52,"Te","Tellurium",127.6,"4d^105s^25p^4",R.color.color5,true)
        val periodictableModel89=ModelPeriodicTable(53,"I","Iodine",126.904,"4d^105s^25p^5",R.color.color7,true)
        val periodictableModel90=ModelPeriodicTable(54,"Xe","Xenon",131.294,"4d^105s^25p^6",R.color.color8,true)

        val periodictableModel91=ModelPeriodicTable(55,"Cs","Cesium",132.905,"[Xe]6s^1",R.color.color1,true)
        val periodictableModel92=ModelPeriodicTable(56,"Ba","Barium",137.328,"6s^2",R.color.color2,true)
        val periodictableModel93=ModelPeriodicTable(57,"","",0.0,"",R.color.black,true)
        val periodictableModel94=ModelPeriodicTable(72,"Hf","Hafnium",178.49,"4f^145d^26s^2",R.color.color3,true)
        val periodictableModel95=ModelPeriodicTable(73,"Ta","Tantalum",180.948,"4f^145d^36s^2",R.color.color3,true)
        val periodictableModel96=ModelPeriodicTable(74,"W","Tungsten",183.85,"4f^145d^46s^2",R.color.color3,true)
        val periodictableModel97=ModelPeriodicTable(75,"Re","Rhenium",186.207,"4f^145d^56s^2",R.color.color3,true)
        val periodictableModel98=ModelPeriodicTable(76,"Os","Osmium",190.23,"4f^145d^66s^2",R.color.color3,true)
        val periodictableModel99=ModelPeriodicTable(77,"Ir","Iridium",192.22,"4f^145d^76s^2",R.color.color3,true)
        val periodictableModel100=ModelPeriodicTable(78,"Pt","Platinum",195.08,"4f^145d^96s^1",R.color.color3,true)
        val periodictableModel101=ModelPeriodicTable(79,"Au","Gold",196.967,"4f^145d^106s^1",R.color.color3,true)
        val periodictableModel102=ModelPeriodicTable(80,"Hg","Mercury",200.59,"4f^145d^106s^2",R.color.color3,true)
        val periodictableModel103=ModelPeriodicTable(81,"Tl","Thallium",204.383,"4f^145d^106s^26p^1",R.color.color4,true)
        val periodictableModel104=ModelPeriodicTable(82,"Pb","Lead",207.2,"4f^145d^106s^26p^2",R.color.color4,true)
        val periodictableModel105=ModelPeriodicTable(83,"Bi","Bismuth",208.980,"4f^145d^106s^26p^3",R.color.color4,true)
        val periodictableModel106=ModelPeriodicTable(84,"Po","Polonium",208.982,"4f^145d^106s^26p^4",R.color.color5,true)
        val periodictableModel107=ModelPeriodicTable(85,"At","Astatine",209.987,"4f^145d^106s^26p^5",R.color.color7,true)
        val periodictableModel108=ModelPeriodicTable(86,"Rn","Radon",222.018,"4f^145d^106s^26p^6",R.color.color8,true)


        val periodictableModel109=ModelPeriodicTable(87,"Fr","Francium",223.020,"[Pn]7s^1",R.color.color1,true)
        val periodictableModel110=ModelPeriodicTable(88,"Ra","Radium",226.025,"7s^2",R.color.color2,true)
        val periodictableModel111=ModelPeriodicTable(89,"","",0.0,"",R.color.black,true)
        val periodictableModel112=ModelPeriodicTable(104,"Rf","Rutherfordium",261.0,"5f^146d^27s^2",R.color.color3,true)
        val periodictableModel113=ModelPeriodicTable(105,"Db","Dubnium",262.0,"5f^146d^37s^2",R.color.color3,true)
        val periodictableModel114=ModelPeriodicTable(106,"Sg","Seaborgium",266.0,"5f^146d^47s^2",R.color.color3,true)
        val periodictableModel115=ModelPeriodicTable(107,"Bh","Bohrium",264.0,"5f^146d^57s^2",R.color.color3,true)
        val periodictableModel116=ModelPeriodicTable(108,"Hs","Hassium",269.0,"5f^146d^67s^2",R.color.color3,true)
        val periodictableModel117=ModelPeriodicTable(109,"Mt","Meitnerium",278.0,"5f^146d^77s^2",R.color.color3,true)
        val periodictableModel118=ModelPeriodicTable(110,"Ds","Darmstadtium",281.0,"5f^146d^97s^1",R.color.color3,true)
        val periodictableModel119=ModelPeriodicTable(111,"Rg","Roentgenium",280.0,"5f^146d^107s^1",R.color.color3,true)
        val periodictableModel120=ModelPeriodicTable(112,"Cn","Copernicium",285.0,"5f^146d^107s^2",R.color.color3,true)
        val periodictableModel121=ModelPeriodicTable(113,"Uut","Nihonium",286.0,"5f^146d^107s^27p^1",R.color.color4,true)
        val periodictableModel122=ModelPeriodicTable(114,"Fl","Flerovium",289.0,"5f^146d^107s^27p^2",R.color.color4,true)
        val periodictableModel123=ModelPeriodicTable(115,"Uup","Moscovium",289.0,"5f^146d^107s^27p^3",R.color.color4,true)
        val periodictableModel124=ModelPeriodicTable(116,"Lv","Livermorium",293.0,"5f^146d^107s^27p^4",R.color.color4,true)
        val periodictableModel125=ModelPeriodicTable(117,"Uus","Tennessine",294.0,"5f^146d^107s^27p^5",R.color.color7,true)
        val periodictableModel126=ModelPeriodicTable(118,"Uuo","Oganesson",294.0,"5f^146d^107s^27p^6",R.color.color8,true)

        val periodictableModel127=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel128=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel129=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel130=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel131=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel132=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel133=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel134=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel135=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel136=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel137=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel138=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel139=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel140=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel141=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel142=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel143=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel144=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)

        val periodictableModel145=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel146=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel147=ModelPeriodicTable(57,"La","Lanthanum",138.905,"5d^16s^2",R.color.color9,true)
        val periodictableModel148=ModelPeriodicTable(58,"Ce","Cerium",140.116,"[Xe]4f^26s^2",R.color.color9,true)
        val periodictableModel149=ModelPeriodicTable(59,"Pr","Preseadymium",140.908,"4f^36s^2",R.color.color9,true)
        val periodictableModel150=ModelPeriodicTable(60,"Nd","Neodymium",144.243,"4f^46s^2",R.color.color9,true)
        val periodictableModel151=ModelPeriodicTable(61,"Pm","Promethium",144.913,"4f^56s^2",R.color.color9,true)
        val periodictableModel152=ModelPeriodicTable(62,"Sm","Samarium",150.36,"4f^76s^2",R.color.color9,true)
        val periodictableModel153=ModelPeriodicTable(63,"Eu","Europium",151.964,"4f^75d^16s^2",R.color.color9,true)
        val periodictableModel154=ModelPeriodicTable(64,"Gd","Gadoilnium",157.25,"4f^96s^2",R.color.color9,true)
        val periodictableModel155=ModelPeriodicTable(65,"Tb","Terbium",158.925,"4f^106s^2",R.color.color9,true)
        val periodictableModel156=ModelPeriodicTable(66,"Dy","Dysprostium",162.500,"4f^116s^2",R.color.color9,true)
        val periodictableModel157=ModelPeriodicTable(67,"Ho","Holmium",164.930,"4f^126s^2",R.color.color9,true)
        val periodictableModel158=ModelPeriodicTable(68,"Er","Erbium",167.259,"4f^136s^2",R.color.color9,true)
        val periodictableModel159=ModelPeriodicTable(69,"Tm","Thullium",168.934,"4f^146s^2",R.color.color9,true)
        val periodictableModel160=ModelPeriodicTable(70,"Yb","Ytterbium",173.055,"4f^145d^16s^2",R.color.color9,true)
        val periodictableModel161=ModelPeriodicTable(71,"Lu","Lutetlium",174.967,"4f^145d^16s^3",R.color.color9,true)
        val periodictableModel162=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)

        val periodictableModel163=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel164=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)
        val periodictableModel165=ModelPeriodicTable(89,"Ac","Actinium",227.028,"6d^17s^2",R.color.color10,true)
        val periodictableModel166=ModelPeriodicTable(90,"Th","Thorium",232.038,"[Rn]6d^27s^2",R.color.color10,true)
        val periodictableModel167=ModelPeriodicTable(91,"Pa","Protactinium",231.036,"5f^26d^17s^2",R.color.color10,true)
        val periodictableModel168=ModelPeriodicTable(92,"U","Uranium",238.029,"5f^36d^17s^2",R.color.color10,true)
        val periodictableModel169=ModelPeriodicTable(93,"Np","Neptunium",237.048,"5f^46d^17s^2",R.color.color10,true)
        val periodictableModel170=ModelPeriodicTable(94,"Pu","Plotonium",244.064,"5f^67s^2",R.color.color10,true)
        val periodictableModel171=ModelPeriodicTable(95,"Am","Americium",243.061,"5f^77s^2",R.color.color10,true)
        val periodictableModel172=ModelPeriodicTable(96,"Cm","Curium",247.070,"5f^76d^17s^2",R.color.color10,true)
        val periodictableModel173=ModelPeriodicTable(97,"Bk","Berkelium",247.070,"5f^97s^2",R.color.color10,true)
        val periodictableModel174=ModelPeriodicTable(98,"Cf","Californium",251.080,"5f^107s^2",R.color.color10,true)
        val periodictableModel175=ModelPeriodicTable(99,"Es","Einsteinium",254.0,"5f^117s^2",R.color.color10,true)
        val periodictableModel176=ModelPeriodicTable(100,"Fm","Fermium",257.095,"5f^127s^2",R.color.color10,true)
        val periodictableModel177=ModelPeriodicTable(101,"Md","Mendelevium",258.1,"5f^137s^2",R.color.color10,true)
        val periodictableModel178=ModelPeriodicTable(102,"No","Nobellum",259.101,"5f^147s^2",R.color.color10,true)
        val periodictableModel179=ModelPeriodicTable(103,"Lr","Lawrencium",262.0,"5f^146d^17s^2",R.color.color10,true)
        val periodictableModel180=ModelPeriodicTable(200,"x","NotVisible",0.0,"200",R.color.black,false)


        periodicTableList.add(periodictableModel1)
        periodicTableList.add(periodictableModel19)
        periodicTableList.add(periodictableModel37)
        periodicTableList.add(periodictableModel55)
        periodicTableList.add(periodictableModel73)
        periodicTableList.add(periodictableModel91)
        periodicTableList.add(periodictableModel109)
        periodicTableList.add(periodictableModel127)
        periodicTableList.add(periodictableModel145)
        periodicTableList.add(periodictableModel163)


        periodicTableList.add(periodictableModel2)
        periodicTableList.add(periodictableModel20)
        periodicTableList.add(periodictableModel38)
        periodicTableList.add(periodictableModel56)
        periodicTableList.add(periodictableModel74)
        periodicTableList.add(periodictableModel92)
        periodicTableList.add(periodictableModel110)
        periodicTableList.add(periodictableModel128)
        periodicTableList.add(periodictableModel146)
        periodicTableList.add(periodictableModel164)

        periodicTableList.add(periodictableModel3)
        periodicTableList.add(periodictableModel21)
        periodicTableList.add(periodictableModel39)
        periodicTableList.add(periodictableModel57)
        periodicTableList.add(periodictableModel75)
        periodicTableList.add(periodictableModel93)
        periodicTableList.add(periodictableModel111)
        periodicTableList.add(periodictableModel129)
        periodicTableList.add(periodictableModel147)
        periodicTableList.add(periodictableModel165)


        periodicTableList.add(periodictableModel4)
        periodicTableList.add(periodictableModel22)
        periodicTableList.add(periodictableModel40)
        periodicTableList.add(periodictableModel58)
        periodicTableList.add(periodictableModel76)
        periodicTableList.add(periodictableModel94)
        periodicTableList.add(periodictableModel112)
        periodicTableList.add(periodictableModel130)
        periodicTableList.add(periodictableModel148)
        periodicTableList.add(periodictableModel166)

        periodicTableList.add(periodictableModel5)
        periodicTableList.add(periodictableModel23)
        periodicTableList.add(periodictableModel41)
        periodicTableList.add(periodictableModel59)
        periodicTableList.add(periodictableModel77)
        periodicTableList.add(periodictableModel95)
        periodicTableList.add(periodictableModel113)
        periodicTableList.add(periodictableModel131)
        periodicTableList.add(periodictableModel149)
        periodicTableList.add(periodictableModel167)

        periodicTableList.add(periodictableModel6)
        periodicTableList.add(periodictableModel24)
        periodicTableList.add(periodictableModel42)
        periodicTableList.add(periodictableModel60)
        periodicTableList.add(periodictableModel78)
        periodicTableList.add(periodictableModel96)
        periodicTableList.add(periodictableModel114)
        periodicTableList.add(periodictableModel132)
        periodicTableList.add(periodictableModel150)
        periodicTableList.add(periodictableModel168)

        periodicTableList.add(periodictableModel7)
        periodicTableList.add(periodictableModel25)
        periodicTableList.add(periodictableModel43)
        periodicTableList.add(periodictableModel61)
        periodicTableList.add(periodictableModel79)
        periodicTableList.add(periodictableModel97)
        periodicTableList.add(periodictableModel115)
        periodicTableList.add(periodictableModel133)
        periodicTableList.add(periodictableModel151)
        periodicTableList.add(periodictableModel169)

        periodicTableList.add(periodictableModel8)
        periodicTableList.add(periodictableModel26)
        periodicTableList.add(periodictableModel44)
        periodicTableList.add(periodictableModel62)
        periodicTableList.add(periodictableModel80)
        periodicTableList.add(periodictableModel98)
        periodicTableList.add(periodictableModel116)
        periodicTableList.add(periodictableModel134)
        periodicTableList.add(periodictableModel152)
        periodicTableList.add(periodictableModel170)

        periodicTableList.add(periodictableModel9)
        periodicTableList.add(periodictableModel27)
        periodicTableList.add(periodictableModel45)
        periodicTableList.add(periodictableModel63)
        periodicTableList.add(periodictableModel81)
        periodicTableList.add(periodictableModel99)
        periodicTableList.add(periodictableModel117)
        periodicTableList.add(periodictableModel135)
        periodicTableList.add(periodictableModel153)
        periodicTableList.add(periodictableModel171)

        periodicTableList.add(periodictableModel10)
        periodicTableList.add(periodictableModel28)
        periodicTableList.add(periodictableModel46)
        periodicTableList.add(periodictableModel64)
        periodicTableList.add(periodictableModel82)
        periodicTableList.add(periodictableModel100)
        periodicTableList.add(periodictableModel118)
        periodicTableList.add(periodictableModel136)
        periodicTableList.add(periodictableModel154)
        periodicTableList.add(periodictableModel172)

        periodicTableList.add(periodictableModel11)
        periodicTableList.add(periodictableModel29)
        periodicTableList.add(periodictableModel47)
        periodicTableList.add(periodictableModel65)
        periodicTableList.add(periodictableModel83)
        periodicTableList.add(periodictableModel101)
        periodicTableList.add(periodictableModel119)
        periodicTableList.add(periodictableModel137)
        periodicTableList.add(periodictableModel155)
        periodicTableList.add(periodictableModel173)

        periodicTableList.add(periodictableModel12)
        periodicTableList.add(periodictableModel30)
        periodicTableList.add(periodictableModel48)
        periodicTableList.add(periodictableModel66)
        periodicTableList.add(periodictableModel84)
        periodicTableList.add(periodictableModel102)
        periodicTableList.add(periodictableModel120)
        periodicTableList.add(periodictableModel138)
        periodicTableList.add(periodictableModel156)
        periodicTableList.add(periodictableModel174)

        periodicTableList.add(periodictableModel13)
        periodicTableList.add(periodictableModel31)
        periodicTableList.add(periodictableModel49)
        periodicTableList.add(periodictableModel67)
        periodicTableList.add(periodictableModel85)
        periodicTableList.add(periodictableModel103)
        periodicTableList.add(periodictableModel121)
        periodicTableList.add(periodictableModel139)
        periodicTableList.add(periodictableModel157)
        periodicTableList.add(periodictableModel175)

        periodicTableList.add(periodictableModel14)
        periodicTableList.add(periodictableModel32)
        periodicTableList.add(periodictableModel50)
        periodicTableList.add(periodictableModel68)
        periodicTableList.add(periodictableModel86)
        periodicTableList.add(periodictableModel104)
        periodicTableList.add(periodictableModel122)
        periodicTableList.add(periodictableModel140)
        periodicTableList.add(periodictableModel158)
        periodicTableList.add(periodictableModel176)

        periodicTableList.add(periodictableModel15)
        periodicTableList.add(periodictableModel33)
        periodicTableList.add(periodictableModel51)
        periodicTableList.add(periodictableModel69)
        periodicTableList.add(periodictableModel87)
        periodicTableList.add(periodictableModel105)
        periodicTableList.add(periodictableModel123)
        periodicTableList.add(periodictableModel141)
        periodicTableList.add(periodictableModel159)
        periodicTableList.add(periodictableModel177)


        periodicTableList.add(periodictableModel16)
        periodicTableList.add(periodictableModel34)
        periodicTableList.add(periodictableModel52)
        periodicTableList.add(periodictableModel70)
        periodicTableList.add(periodictableModel88)
        periodicTableList.add(periodictableModel106)
        periodicTableList.add(periodictableModel124)
        periodicTableList.add(periodictableModel142)
        periodicTableList.add(periodictableModel160)
        periodicTableList.add(periodictableModel178)

        periodicTableList.add(periodictableModel17)
        periodicTableList.add(periodictableModel35)
        periodicTableList.add(periodictableModel53)
        periodicTableList.add(periodictableModel71)
        periodicTableList.add(periodictableModel89)
        periodicTableList.add(periodictableModel107)
        periodicTableList.add(periodictableModel125)
        periodicTableList.add(periodictableModel143)
        periodicTableList.add(periodictableModel161)
        periodicTableList.add(periodictableModel179)

        periodicTableList.add(periodictableModel18)
        periodicTableList.add(periodictableModel36)
        periodicTableList.add(periodictableModel54)
        periodicTableList.add(periodictableModel72)
        periodicTableList.add(periodictableModel90)
        periodicTableList.add(periodictableModel108)
        periodicTableList.add(periodictableModel126)
        periodicTableList.add(periodictableModel144)
        periodicTableList.add(periodictableModel162)
        periodicTableList.add(periodictableModel180)


//
//        periodicTableList.add(periodictableModel2)
//        periodicTableList.add(periodictableModel3)
//        periodicTableList.add(periodictableModel4)
//        periodicTableList.add(periodictableModel5)
//        periodicTableList.add(periodictableModel6)
//        periodicTableList.add(periodictableModel7)
//        periodicTableList.add(periodictableModel8)
//        periodicTableList.add(periodictableModel9)
//        periodicTableList.add(periodictableModel10)
//        periodicTableList.add(periodictableModel11)
//        periodicTableList.add(periodictableModel12)
//        periodicTableList.add(periodictableModel13)
//        periodicTableList.add(periodictableModel14)
//        periodicTableList.add(periodictableModel15)
//        periodicTableList.add(periodictableModel16)
//        periodicTableList.add(periodictableModel17)
//        periodicTableList.add(periodictableModel18)
//
//        periodicTableList.add(periodictableModel20)
//        periodicTableList.add(periodictableModel21)
//        periodicTableList.add(periodictableModel22)
//        periodicTableList.add(periodictableModel23)
//        periodicTableList.add(periodictableModel24)
//        periodicTableList.add(periodictableModel25)
//        periodicTableList.add(periodictableModel26)
//        periodicTableList.add(periodictableModel27)
//        periodicTableList.add(periodictableModel28)
//        periodicTableList.add(periodictableModel29)
//        periodicTableList.add(periodictableModel30)
//        periodicTableList.add(periodictableModel31)
//        periodicTableList.add(periodictableModel32)
//        periodicTableList.add(periodictableModel33)
//        periodicTableList.add(periodictableModel34)
//        periodicTableList.add(periodictableModel35)
//        periodicTableList.add(periodictableModel36)
//
//        periodicTableList.add(periodictableModel38)
//        periodicTableList.add(periodictableModel39)
//        periodicTableList.add(periodictableModel40)
//        periodicTableList.add(periodictableModel41)
//        periodicTableList.add(periodictableModel42)
//        periodicTableList.add(periodictableModel43)
//        periodicTableList.add(periodictableModel44)
//        periodicTableList.add(periodictableModel45)
//        periodicTableList.add(periodictableModel46)
//        periodicTableList.add(periodictableModel47)
//        periodicTableList.add(periodictableModel48)
//        periodicTableList.add(periodictableModel49)
//        periodicTableList.add(periodictableModel50)
//        periodicTableList.add(periodictableModel51)
//        periodicTableList.add(periodictableModel52)
//        periodicTableList.add(periodictableModel53)
//        periodicTableList.add(periodictableModel54)
//
//        periodicTableList.add(periodictableModel56)
//        periodicTableList.add(periodictableModel57)
//        periodicTableList.add(periodictableModel58)
//        periodicTableList.add(periodictableModel59)
//        periodicTableList.add(periodictableModel60)
//        periodicTableList.add(periodictableModel61)
//        periodicTableList.add(periodictableModel62)
//        periodicTableList.add(periodictableModel63)
//        periodicTableList.add(periodictableModel64)
//        periodicTableList.add(periodictableModel65)
//        periodicTableList.add(periodictableModel66)
//        periodicTableList.add(periodictableModel67)
//        periodicTableList.add(periodictableModel68)
//        periodicTableList.add(periodictableModel69)
//        periodicTableList.add(periodictableModel70)
//        periodicTableList.add(periodictableModel71)
//        periodicTableList.add(periodictableModel72)
//        periodicTableList.add(periodictableModel74)
//        periodicTableList.add(periodictableModel75)
//        periodicTableList.add(periodictableModel76)
//        periodicTableList.add(periodictableModel77)
//        periodicTableList.add(periodictableModel78)
//        periodicTableList.add(periodictableModel79)
//        periodicTableList.add(periodictableModel80)
//        periodicTableList.add(periodictableModel81)
//        periodicTableList.add(periodictableModel82)
//        periodicTableList.add(periodictableModel83)
//        periodicTableList.add(periodictableModel84)
//        periodicTableList.add(periodictableModel85)
//        periodicTableList.add(periodictableModel86)
//        periodicTableList.add(periodictableModel87)
//        periodicTableList.add(periodictableModel88)
//        periodicTableList.add(periodictableModel89)
//        periodicTableList.add(periodictableModel90)
//        periodicTableList.add(periodictableModel92)
//        periodicTableList.add(periodictableModel93)
//        periodicTableList.add(periodictableModel94)
//        periodicTableList.add(periodictableModel95)
//        periodicTableList.add(periodictableModel96)
//        periodicTableList.add(periodictableModel97)
//        periodicTableList.add(periodictableModel98)
//        periodicTableList.add(periodictableModel99)
//        periodicTableList.add(periodictableModel100)
//        periodicTableList.add(periodictableModel101)
//        periodicTableList.add(periodictableModel102)
//        periodicTableList.add(periodictableModel103)
//        periodicTableList.add(periodictableModel104)
//        periodicTableList.add(periodictableModel105)
//        periodicTableList.add(periodictableModel106)
//        periodicTableList.add(periodictableModel107)
//        periodicTableList.add(periodictableModel108)
//        periodicTableList.add(periodictableModel110)
//        periodicTableList.add(periodictableModel111)
//        periodicTableList.add(periodictableModel112)
//        periodicTableList.add(periodictableModel113)
//        periodicTableList.add(periodictableModel114)
//        periodicTableList.add(periodictableModel115)
//        periodicTableList.add(periodictableModel116)
//        periodicTableList.add(periodictableModel117)
//        periodicTableList.add(periodictableModel118)
//        periodicTableList.add(periodictableModel119)
//        periodicTableList.add(periodictableModel120)
//        periodicTableList.add(periodictableModel121)
//        periodicTableList.add(periodictableModel122)
//        periodicTableList.add(periodictableModel123)
//        periodicTableList.add(periodictableModel124)
//        periodicTableList.add(periodictableModel125)
//        periodicTableList.add(periodictableModel126)

        return periodicTableList

    }
}